#! /bin/bash
zip -r ".\source\Assignment01\grade, me(student)\Submission attachment(s)\submission.zip" ".\submission"
cd .\source
java -cp .;.\source\Comp524GraderAll.jar;D:\dewan_backup\Java\Gradescope-Autograder\GradescopeAssignmentSetup\target\classes;C:\Users\dewan\.m2\repository\org\json\json\20171018\json-20171018.jar gradingTools.Comp401Driver --project-requirements  --project-name  Assignment01 --grader-controller AHeadlessGradingManager --headless-path .\source\Assignment01 --headless-start student --headless-end student --course-name Comp524F20 --logger feedback-txt+feedback-json+local-txt+local-json --no-framework-gui --clean-slate student
java -jar GradescopeRunner.jar ".\source\Assignment01\grade, me(student)\Feedback Attachment(s)\results.json" ".\results\results.json"